import React from "react";import{createRoot}from"react-dom/client";import"./styles.css";
const B={phone:"5581999999999",services:[["Corte Tradicional","Acabamento preciso e estilo sob medida.","R$ 45"],["Skin Fade","Degradê na régua, do zero ao acabamento.","R$ 55"],["Barba Premium","Toalha quente, desenho e finalização.","R$ 40"],["Corte + Barba","O combo completo para sair na régua.","R$ 85"]],barbers:[["Lucas","Especialista em Fade","https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=800&q=85"],["Rafael","Barbeiro & Visagista","https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=800&q=85"],["Diego","Especialista em Barba","https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=85"]],gallery:["https://images.unsplash.com/photo-1622288432450-277d0fef5ed6?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1512690459411-b9245aed614b?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1521490683712-8e0f7d6b8f98?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1200&q=85"]};
const wa=(m="Olá! Gostaria de agendar um horário na Iron & Gold.")=>`https://wa.me/${B.phone}?text=${encodeURIComponent(m)}`;
function Header(){return <header><a className="brand" href="#inicio">IRON & GOLD<small>BARBER CLUB</small></a><nav><a href="#servicos">Serviços</a><a href="#barbeiros">Barbeiros</a><a href="#galeria">Galeria</a><a href="#contato">Contato</a></nav><a className="btn mini" href={wa()}>Agendar</a></header>}
function Hero(){return <section id="inicio" className="hero"><div className="shade"/><div className="heroText"><small>BARBER CLUB · ESTILO SEM DESCULPAS</small><h1>Seu estilo.<br/><i>Sua assinatura.</i></h1><p>Cortes precisos, barba impecável e uma experiência feita para quem não abre mão de sair na régua.</p><div className="actions"><a className="btn" href={wa()}>AGENDAR HORÁRIO ↗</a><a href="#servicos" className="link">Ver serviços ↓</a></div><div className="meta">★ 5.0 &nbsp; • &nbsp; Centro · Recife/PE</div></div><div className="side">IRON<br/><b>&</b><br/>GOLD</div></section>}
function Services(){return <section id="servicos" className="section"><div className="top"><div><small>MENU</small><h2>Serviços <i>em destaque</i></h2></div><a className="link" href={wa("Olá! Gostaria de saber os horários disponíveis.")}>Consultar horários ↗</a></div><div className="services">{B.services.map((s,i)=><article className="service" key={s[0]}><span>0{i+1}</span><div><h3>{s[0]}</h3><p>{s[1]}</p></div><strong>{s[2]}</strong></article>)}</div></section>}
function Barbers(){return <section id="barbeiros" className="section dark"><small>NOSSO TIME</small><h2>Quem vai cuidar<br/><i>do seu estilo.</i></h2><div className="barbers">{B.barbers.map(b=><article><img src={b[2]} alt={b[0]}/><h3>{b[0]}</h3><p>{b[1]}</p></article>)}</div></section>}
function Gallery(){return <section id="galeria" className="section"><small>NOSSO TRABALHO</small><h2>Feito na <i>régua.</i></h2><div className="gallery">{B.gallery.map((x,i)=><img key={i} src={x} alt="Trabalho da barbearia"/>)}</div></section>}
function Contact(){return <section id="contato" className="contact"><div><small>ONDE ESTAMOS</small><h2>Seu próximo corte<br/><i>começa aqui.</i></h2><a className="btn black" href={wa()}>AGENDAR PELO WHATSAPP ↗</a></div><div className="info"><div><b>ENDEREÇO</b><p>Av. Principal, 250 — Centro<br/>Recife — PE</p></div><div><b>HORÁRIO</b><p>Seg a Sáb · 09h às 20h</p></div><div><b>INSTAGRAM</b><p>@ironandgold</p></div></div></section>}
function App(){return <><Header/><main><Hero/><section className="intro"><div><small>A EXPERIÊNCIA</small><h2>Mais que um corte.<br/><i>Um momento seu.</i></h2></div><p>Um espaço pensado para unir técnica, personalidade e aquele cuidado que faz você voltar. Escolha seu serviço, fale com seu barbeiro e reserve seu horário.</p></section><Services/><Barbers/><Gallery/><Contact/></main><footer><strong>IRON & GOLD<small>BARBER CLUB</small></strong><p>Página demonstrativa — informações e imagens utilizadas apenas para apresentação do modelo.</p><span>© 2026</span></footer><a className="float" href={wa()}>◔</a></>}
createRoot(document.getElementById("root")).render(<App/>);